const ACTION_TYPES = {
  SET_ORIGIN_AMT: "SET_ORIGIN_AMT",
  SET_DESTINATION_AMT: "SET_DESTINATION_AMT",
  SET_ORIGIN_CURR: "SET_ORIGIN_CURR",
  SET_DESTINATION_CURR: "SET_DESTINATION_CURR",

  REQ_CONVERSION: "REQ_CONVERSION",
  REQ_FEES: "REQ_FEES",

  REC_CONVERSION_SUCCESS: "REC_CONVERSION_SUCCESS",
  REC_FEES_SUCCESS: "REC_FEES_SUCCESS",

  REC_CONVERSION_FAILURE: "REC_CONVERSION_FAILURE",
  REC_FEES_FAILURE: "REC_FEES_FAILURE",
};
export { ACTION_TYPES };
