const ACTION_TYPES = {
  SET_ORIGIN_AMT: "SET_ORIGIN_AMT",
  SET_DESTINATION_AMT: "SET_DESTINATION_AMT",
  REQ_CONVERSION: "REQ_CONVERSION",
  REC_CONVERSION_SUCCESS: "REC_CONVERSION_SUCCESS",
  REC_CONVERSION_FAILURE: "REC_CONVERSION_FAILURE",
  REQ_FEES: "REQ_FEES",
  REC_FEES_SUCCESS: "REC_FEES_SUCCESS",
  REC_FEES_FAILURE: "REC_FEES_FAILURE",
};
export { ACTION_TYPES };
